const ny = {
    stateAbbr: "NY",
    stateFull: "New York",
    cities: [
        "Adams",
        "Addison",
        "Afton",
        "Airmont",
        "Akron",
        "Albany",
        "Albion",
        "Alden",
        "Alexander",
        "Alexandria Bay",
        "Alfred",
        "Allegany",
        "Almond",
        "Altamont",
        "Ames",
        "Amityville",
        "Amsterdam",
        "Andover",
        "Angelica",
        "Angola",
        "Antwerp",
        "Arcade",
        "Ardsley",
        "Argyle",
        "Arkport",
        "Asharoken",
        "Athens",
        "Atlantic Beach",
        "Attica",
        "Auburn",
        "Aurora",
        "Avoca",
        "Avon",
        "Babylon",
        "Bainbridge",
        "Baldwinsville",
        "Ballston Spa",
        "Barker",
        "Batavia",
        "Bath",
        "Baxter Estates",
        "Bayville",
        "Beacon",
        "Bellerose",
        "Belle Terre",
        "Bellport",
        "Belmont",
        "Bemus Point",
        "Bergen",
        "Binghamton",
        "Black River",
        "Blasdell",
        "Bloomfield",
        "Bloomingburg",
        "Bolivar",
        "Boonville",
        "Brewster",
        "Briarcliff Manor",
        "Brightwaters",
        "Broadalbin",
        "Brockport",
        "Brocton",
        "Bronxville",
        "Brookville",
        "Brownville",
        "Brushton",
        "Buchanan",
        "Buffalo",
        "Burdett",
        "Burke",
        "Caledonia",
        "Cambridge",
        "Camden",
        "Camillus",
        "Canajoharie",
        "Canandaigua",
        "Canaseraga",
        "Canastota",
        "Candor",
        "Canisteo",
        "Canton",
        "Cape Vincent",
        "Carthage",
        "Cassadaga",
        "Castile",
        "Castleton-on-Hudson",
        "Castorland",
        "Cato",
        "Catskill",
        "Cattaraugus",
        "Cayuga",
        "Cayuga Heights",
        "Cazenovia",
        "Cedarhurst",
        "Celoron",
        "Central Square",
        "Centre Island",
        "Champlain",
        "Chateaugay",
        "Chatham",
        "Chaumont",
        "Cherry Valley",
        "Chester",
        "Chestnut Ridge",
        "Chittenango",
        "Churchville",
        "Clayton",
        "Clayville",
        "Cleveland",
        "Clifton Springs",
        "Clinton",
        "Clyde",
        "Cobleskill",
        "Cohocton",
        "Cohoes",
        "Cold Brook",
        "Cold Spring",
        "Colonie",
        "Constableville",
        "Cooperstown",
        "Copenhagen",
        "Corfu",
        "Corinth",
        "Corning",
        "Cornwall-on-Hudson",
        "Cortland",
        "Cove Neck",
        "Coxsackie",
        "Croghan",
        "Croton-on-Hudson",
        "Cuba",
        "Dannemora",
        "Dansville",
        "Deferiet",
        "Delanson",
        "Delevan",
        "Delhi",
        "Depew",
        "Deposit",
        "Dering Harbor",
        "DeRuyter",
        "Dexter",
        "Dobbs Ferry",
        "Dolgeville",
        "Dresden",
        "Dryden",
        "Dundee",
        "Dunkirk",
        "Earlville",
        "East Aurora",
        "East Hampton",
        "East Hills",
        "East Nassau",
        "East Rochester",
        "East Rockaway",
        "East Syracuse",
        "East Williston",
        "Elba",
        "Elbridge",
        "Ellenville",
        "Ellicottville",
        "Ellisburg",
        "Elmira",
        "Elmira Heights",
        "Elmsford",
        "Endicott",
        "Esperance",
        "Evans Mills",
        "Fabius",
        "Fair Haven",
        "Fairport",
        "Falconer",
        "Farmingdale",
        "Farnham",
        "Fayetteville",
        "Fishkill",
        "Fleischmanns",
        "Floral Park",
        "Florida",
        "Flower Hill",
        "Fonda",
        "Fort Ann",
        "Fort Edward",
        "Fort Johnson",
        "Fort Plain",
        "Frankfort",
        "Franklin",
        "Franklinville",
        "Fredonia",
        "Freeport",
        "Freeville",
        "Fulton",
        "Fultonville",
        "Gainesville",
        "Galway",
        "Garden",
        "Geneseo",
        "Geneva",
        "Gilbertsville",
        "Glen Cove",
        "Glen Park",
        "Glens Falls",
        "Gloversville",
        "Goshen",
        "Gouverneur",
        "Gowanda",
        "Grand View-on-Hudson",
        "Granville",
        "Great Neck",
        "Great Neck Estates",
        "Great Neck Plaza",
        "Greene",
        "Green Island",
        "Greenport",
        "Greenwich",
        "Greenwood Lake",
        "Groton",
        "Hagaman",
        "Hamburg",
        "Hamilton",
        "Hammond",
        "Hammondsport",
        "Hancock",
        "Hannibal",
        "Harriman",
        "Harrison",
        "Hastings-on-Hudson",
        "Haverstraw",
        "Head of the Harbor",
        "Hempstead",
        "Herkimer",
        "Heuvelton",
        "Hewlett Bay Park",
        "Hewlett Harbor",
        "Hewlett Neck",
        "Highland Falls",
        "Hillburn",
        "Hilton",
        "Hobart",
        "Holland Patent",
        "Holley",
        "Homer",
        "Honeoye Falls",
        "Hoosick Falls",
        "Hornell",
        "Horseheads",
        "Hudson",
        "Hudson Falls",
        "Hunter",
        "Huntington Bay",
        "Ilion",
        "Interlaken",
        "Irvington",
        "Islandia",
        "Island Park",
        "Ithaca",
        "Jamestown",
        "Jeffersonville",
        "Johnson",
        "Johnstown",
        "Jordan",
        "Kaser",
        "Kenmore",
        "Kensington",
        "Kinderhook",
        "Kings Point",
        "Kingston",
        "Kiryas Joel",
        "Lackawanna",
        "Lacona",
        "Lake George",
        "Lake Grove",
        "Lake Placid",
        "Lake Success",
        "Lakewood",
        "Lancaster",
        "Lansing",
        "Larchmont",
        "Lattingtown",
        "Laurel Hollow",
        "Laurens",
        "Lawrence",
        "Leicester",
        "Le Roy",
        "Lewiston",
        "Liberty",
        "Lima",
        "Lindenhurst",
        "Lisle",
        "Little Falls",
        "Little Valley",
        "Liverpool",
        "Livonia",
        "Lloyd Harbor",
        "Lockport",
        "Lodi",
        "Long Beach",
        "Lowville",
        "Lynbrook",
        "Lyndonville",
        "Lyons Falls",
        "McGraw",
        "Madison",
        "Malone",
        "Malverne",
        "Mamaroneck",
        "Manchester",
        "Manlius",
        "Mannsville",
        "Manorhaven",
        "Marathon",
        "Marcellus",
        "Margaretville",
        "Massapequa Park",
        "Massena",
        "Matinecock",
        "Maybrook",
        "Mayfield",
        "Mayville",
        "Mechanicville",
        "Medina",
        "Menands",
        "Meridian",
        "Mexico",
        "Middleburgh",
        "Middleport",
        "Middletown",
        "Middleville",
        "Milford",
        "Millbrook",
        "Millerton",
        "Mill Neck",
        "Millport",
        "Mineola",
        "Minoa",
        "Mohawk",
        "Monroe",
        "Montebello",
        "Montgomery",
        "Monticello",
        "Montour Falls",
        "Moravia",
        "Morris",
        "Morrisville",
        "Mount Kisco",
        "Mount Morris",
        "Mount Vernon",
        "Munnsville",
        "Munsey Park",
        "Muttontown",
        "Naples",
        "Nassau",
        "Nelliston",
        "Nelsonville",
        "Newark",
        "Newark Valley",
        "New Berlin",
        "Newburgh",
        "New Hartford",
        "New Hempstead",
        "New Hyde Park",
        "New Paltz",
        "Newport",
        "New Rochelle",
        "New Square",
        "New York",
        "New York Mills",
        "Niagara Falls",
        "Nichols",
        "Nissequogue",
        "North Collins",
        "North Haven",
        "North Hills",
        "North Hornell",
        "Northport",
        "North Syracuse",
        "North Tonawanda",
        "Northville",
        "Norwich",
        "Norwood",
        "Nunda",
        "Nyack",
        "Oakfield",
        "Ocean Beach",
        "Odessa",
        "Ogdensburg",
        "Old Brookville",
        "Old Field",
        "Old Westbury",
        "Olean",
        "Oneida",
        "Oneida Castle",
        "Oneonta",
        "Orchard Park",
        "Oriskany",
        "Oriskany Falls",
        "Ossining",
        "Oswego",
        "Otego",
        "Otisville",
        "Ovid",
        "Owego",
        "Oxford",
        "Oyster Bay Cove",
        "Painted Post",
        "Palatine Bridge",
        "Palmyra",
        "Panama",
        "Parish",
        "Patchogue",
        "Pawling",
        "Peekskill",
        "Pelham",
        "Pelham Manor",
        "Penn Yan",
        "Perry",
        "Phelps",
        "Philadelphia",
        "Philmont",
        "Phoenix",
        "Piermont",
        "Pittsford",
        "Plandome",
        "Plandome Heights",
        "Plandome Manor",
        "Plattsburgh",
        "Pleasantville",
        "Poland",
        "Pomona",
        "Poquott",
        "Port Byron",
        "Port Chester",
        "Port Dickinson",
        "Port Jefferson",
        "Port Jervis",
        "Port Leyden",
        "Portville",
        "Port Washington North",
        "Potsdam",
        "Poughkeepsie",
        "Pulaski",
        "Quogue",
        "Ravena",
        "Red Creek",
        "Red Hook",
        "Remsen",
        "Rensselaer",
        "Rensselaer Falls",
        "Rhinebeck",
        "Richburg",
        "Richfield Springs",
        "Richmondville",
        "Richville",
        "Riverside",
        "Rochester",
        "Rockville Centre",
        "Rome",
        "Roslyn",
        "Roslyn Estates",
        "Roslyn Harbor",
        "Round Lake",
        "Rouses Point",
        "Rushville",
        "Russell Gardens",
        "Rye",
        "Rye Brook",
        "Sackets Harbor",
        "Saddle Rock",
        "Sagaponack",
        "Sag Harbor",
        "St. Johnsville",
        "Salamanca",
        "Saltaire",
        "Sands Point",
        "Sandy Creek",
        "Saranac Lake",
        "Saratoga Springs",
        "Saugerties",
        "Savona",
        "Scarsdale",
        "Schaghticoke",
        "Schenectady",
        "Schoharie",
        "Schuylerville",
        "Scotia",
        "Scottsville",
        "Sea Cliff",
        "Sharon Springs",
        "Sherburne",
        "Sherman",
        "Sherrill",
        "Shoreham",
        "Shortsville",
        "Sidney",
        "Silver Creek",
        "Silver Springs",
        "Sinclairville",
        "Skaneateles",
        "Sleepy Hollow",
        "Sloan",
        "Sloatsburg",
        "Smyrna",
        "Sodus",
        "Sodus Point",
        "Solvay",
        "Southampton",
        "South Blooming Grove",
        "South Corning",
        "South Dayton",
        "South Floral Park",
        "South Glens Falls",
        "Speculator",
        "Spencer",
        "Spencerport",
        "Spring Valley",
        "Springville",
        "Stamford",
        "Stewart Manor",
        "Stillwater",
        "Suffern",
        "Sylvan Beach",
        "Syracuse",
        "Tannersville",
        "Tarrytown",
        "Theresa",
        "Thomaston",
        "Tivoli",
        "Tonawanda",
        "Troy",
        "Trumansburg",
        "Tuckahoe",
        "Tully",
        "Tupper Lake",
        "Turin",
        "Tuxedo",
        "Tuxedo Park",
        "Unadilla",
        "Union Springs",
        "Unionville",
        "Upper Brookville",
        "Upper Nyack",
        "Utica",
        "Valatie",
        "Valley Falls",
        "Valley Stream",
        "Vernon",
        "Victor",
        "Victory",
        "Village of the Branch",
        "Voorheesville",
        "Waddington",
        "Walden",
        "Walton",
        "Wampsville",
        "Wappingers Falls",
        "Warsaw",
        "Warwick",
        "Washingtonville",
        "Waterford",
        "Waterloo",
        "Watertown",
        "Waterville",
        "Watervliet",
        "Watkins Glen",
        "Waverly",
        "Wayland",
        "Webster",
        "Weedsport",
        "Wellsburg",
        "Wellsville",
        "Wesley Hills",
        "Westbury",
        "West Carthage",
        "Westfield",
        "Westhampton Beach",
        "West Hampton Dunes",
        "West Haverstraw",
        "West Winfield",
        "Whitehall",
        "White Plains",
        "Whitesboro",
        "Whitney Point",
        "Williamsville",
        "Williston Park",
        "Wilson",
        "Windsor",
        "Wolcott",
        "Woodbury",
        "Woodridge",
        "Woodsburgh",
        "Wurtsboro",
        "Wyoming",
        "Yonkers",
        "Yorkville",
        "Youngstown",
    ]
}
const locations = [ny];
export default locations;